version: "3"

services:
  app:
    image: cbsan/flutter
    working_dir: /usr/src
    volumes:
      - ./my_app:/usr/src
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - storage_avd:/root/.android/avd
      - storage_gradle:/root/.gradle
    tty: true
    privileged: true
    environment:
      DISPLAY: $DISPLAY
volumes:
  storage_avd:
  storage_gradle:
